# Generated by Django 3.0.6 on 2020-05-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jokes',
            old_name='name',
            new_name='joke',
        ),
    ]
